version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      machine:
        image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.
        steps:
          - node/with-cache:
              steps:
                - run: npm install
                - run: npm run seed
                - run: npm run jest --detectOpenHandles --coverage
workflows:
    build-and-test:
      jobs:
        - build-and-test
